version: "3.1"
services:
  postgres:
    image: zbigmic300/silownia-db
    networks:
      - db_net
    ports:
      - "5433:5432"
  app:
    image: zbigmic300/silownia-app
    ports:
      - "4000:5090"
    networks:
      - db_net
    depends_on:
      - postgres
    links:
      - postgres:postgres
networks:
  db_net: